services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw 
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/liv/postgresql/data
volumes:
  pgdata:        